debug: false
parallel:
  dsg: true
  ol: true

dsg:
  disk:
    - "E:"
    - "D:"
  delay: 30

ol:
  delay: 2
  patterns:
    - title: xyplorer
      opacity: 210
    - title: XYplorer
      opacity: 210
    - title: "- Microsoft​ Edge$"
      opacity: 200
    - title: "- Visual Studio Code"
      opacity: 180
