debug: false
parallel:
  dsg: true
  ol: true

dsg:
  disk:
    - "E:"
  #  delay: 这样不设置会置空, 而不是取 default
  delay: 30

ol:
  delay: 2
  patterns:
    - title: "(XY|xy)plorer"
      opacity: 200
    - title: "设置$"
      opacity: 220

    - title: "- Microsoft​ Edge Beta$"
      # opacity: 200
      opacity: 255

    - title: "- Visual Studio Code$"
      # opacity: 240
      opacity: 220

    # terminal
    - title: "cmd.exe$"
      opacity: 210
    - title: "PowerShell$"
      opacity: 210
    - title: "^Xterminal$"
      opacity: 230

    # app
    - title: "^微信$"
      opacity: 200
    - title: "^Steam$"
      opacity: 220
      # opacity: 255
    - title: "^UniGetUI$"
      opacity: 240
    - title: "- WPS Office$"
      opacity: 200
    - title: "- PotPlayer$"
      opacity: 250
